systemd:
  units:
  - name: update-engine.service
    mask: true
  - name: locksmithd.service
    mask: true
  - name: docker.service
    enable: true
    dropins:
      - name: 20-docker-opts.conf
        contents: |
          [Service]
          Environment="DOCKER_OPTS=--log-driver json-file --log-opt max-size=1m --log-opt mode=non-blocking --log-opt max-buffer-size=1m"
