- name: Create RECAP security group
  os_security_group:
    state: present
    name: sec_recap_demo
    description: security group rule for recap infrastructure demo
- name: Create recap security group for SSH
  os_security_group_rule:
    security_group: sec_recap_demo
    protocol: tcp
    state: present
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
- name: Create recap security group rule for HTTPS
  os_security_group_rule:
    security_group: sec_recap_demo
    state: present
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0
- name: Create recap security group rule for HTTP
  os_security_group_rule:
    security_group: sec_recap_demo
    state: present
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
- name: Create recap security group rule for HTTP-alt
  os_security_group_rule:
    security_group: sec_recap_demo
    state: present
    protocol: tcp
    port_range_min: 8080
    port_range_max: 8080
    remote_ip_prefix: 0.0.0.0/0
- name: Create rancher ports
  os_security_group_rule:
    security_group: sec_recap_demo
    state: present
    protocol: udp
    port_range_min: 500
    port_range_max: 500
    remote_ip_prefix: 192.168.0.0/16
- name: Create rancher ports 2
  os_security_group_rule:
    security_group: sec_recap_demo
    state: present
    protocol: udp
    port_range_min: 4500
    port_range_max: 4500
